services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://flask_user:flask_password@db:5432/flask_db
    depends_on:
      - db


  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: loupgarou
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: loupgarou_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./:/docker-entrypoint-initdb.d


volumes:
  postgres_data: