FROM python:3.12-slim


# Installer les dépendances nécessaires pour psycopg2 (libpq-dev, gcc)
RUN apt-get update && apt-get install -y libpq-dev gcc


WORKDIR /app


# Copier le fichier requirements.txt
COPY requirements.txt .


# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt


# Copier le reste du code
COPY . .


# Lancer l'application
CMD ["python", "app.py"]